//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_JOB_POST()
        {
            this.TB_JOB_APPLICAITON = new HashSet<TB_JOB_APPLICAITON>();
            this.TB_JOB_POST_SKILL_KEYWORD = new HashSet<TB_JOB_POST_SKILL_KEYWORD>();
            this.TB_RECOMMENDED_JOB_POST = new HashSet<TB_RECOMMENDED_JOB_POST>();
            this.TB_RELATED_JOB_POST = new HashSet<TB_RELATED_JOB_POST>();
            this.TB_RELATED_JOB_POST1 = new HashSet<TB_RELATED_JOB_POST>();
        }
    
        public int Job_ID { get; set; }
        public string Job_Position { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public string Job_Ref_No { get; set; }
        public string Site_Ref_No { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Post_Start_Date { get; set; }
        public Nullable<System.DateTime> Post_End_Date { get; set; }
        public Nullable<int> Employment_Type { get; set; }
        public Nullable<int> Part_Time_HR_Week { get; set; }
        public string Employ_Start_Date { get; set; }
        public string Employ_End_Date { get; set; }
        public Nullable<int> Work_Experience { get; set; }
        public Nullable<int> Education_Level { get; set; }
        public Nullable<int> Career_Level { get; set; }
        public Nullable<int> Paid_Type { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<bool> Salary_Visibility { get; set; }
        public Nullable<int> Job_Industry { get; set; }
        public string Job_Function_Other { get; set; }
        public Nullable<int> Work_Location { get; set; }
        public string Work_Location_Other { get; set; }
        public string Benefit { get; set; }
        public string Job_Description { get; set; }
        public Nullable<int> View_Count { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> Original_Job_ID { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        public virtual TB_COMPANY TB_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_APPLICAITON> TB_JOB_APPLICAITON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST_SKILL_KEYWORD> TB_JOB_POST_SKILL_KEYWORD { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY1 { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY2 { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY3 { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY4 { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY5 { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY6 { get; set; }
        public virtual TB_MASTER_DATA_SUB_CATEGORY TB_MASTER_DATA_SUB_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RECOMMENDED_JOB_POST> TB_RECOMMENDED_JOB_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RELATED_JOB_POST> TB_RELATED_JOB_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RELATED_JOB_POST> TB_RELATED_JOB_POST1 { get; set; }
    }
}
