//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_JOB_SEEKER()
        {
            this.TB_JOB_POST_VIEW_HISTORY = new HashSet<TB_JOB_POST_VIEW_HISTORY>();
            this.TB_JOB_SEEKER_COVER_LETTER = new HashSet<TB_JOB_SEEKER_COVER_LETTER>();
            this.TB_JOB_SEEKER_CV = new HashSet<TB_JOB_SEEKER_CV>();
            this.TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION = new HashSet<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION>();
            this.TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY = new HashSet<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY>();
            this.TB_RECOMMENDED_JOB_POST = new HashSet<TB_RECOMMENDED_JOB_POST>();
        }
    
        public int JobSeeker_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Chinese_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Account_Type { get; set; }
        public string Country_Code { get; set; }
        public string Area_Code { get; set; }
        public string Contact_No { get; set; }
        public Nullable<bool> Profile_Visibility { get; set; }
        public Nullable<bool> News_Subscription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Default_CV { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> Default_Cover_Letter { get; set; }
        public Nullable<System.DateTime> Last_Logon_date { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST_VIEW_HISTORY> TB_JOB_POST_VIEW_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_COVER_LETTER> TB_JOB_SEEKER_COVER_LETTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_CV> TB_JOB_SEEKER_CV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION> TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY> TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RECOMMENDED_JOB_POST> TB_RECOMMENDED_JOB_POST { get; set; }
    }
}
