//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_APPLICAITON
    {
        public int JobApplication_ID { get; set; }
        public Nullable<int> JobSeeker_CV_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Cover_Letter { get; set; }
        public Nullable<int> Relevance { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<bool> Has_Requested { get; set; }
        public Nullable<int> Creator_Type { get; set; }
        public Nullable<int> Modifier_Type { get; set; }
        public Nullable<int> Expected_Salary { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
    
        public virtual TB_JOB_POST TB_JOB_POST { get; set; }
        public virtual TB_JOB_SEEKER_CV TB_JOB_SEEKER_CV { get; set; }
    }
}
