//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION()
        {
            this.TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY = new HashSet<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY>();
        }
    
        public int JobSeeker_Subs_ID { get; set; }
        public Nullable<int> JobSeeker_ID { get; set; }
        public Nullable<int> Job_Function { get; set; }
        public Nullable<int> Paid_Type { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Education_Level { get; set; }
        public Nullable<int> Employment_Type { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<int> Search_Type { get; set; }
        public string Search_Keyword { get; set; }
    
        public virtual TB_JOB_SEEKER TB_JOB_SEEKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY> TB_JOB_SEEKER_SEARCH_CRITERIA_SUBSCRIPTION_NOTIFICATION_HISTORY { get; set; }
    }
}
