//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_POST_VIEW_HISTORY
    {
        public int Job_ID { get; set; }
        public int JobSeeker_ID { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
    
        public virtual TB_JOB_SEEKER TB_JOB_SEEKER { get; set; }
    }
}
