//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTPEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MASTER_DATA_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MASTER_DATA_CATEGORY()
        {
            this.TB_JOB_POST = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST1 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST2 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST3 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST4 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST5 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST6 = new HashSet<TB_JOB_POST>();
            this.TB_JOB_SEEKER_JOB_FUNCTION = new HashSet<TB_JOB_SEEKER_JOB_FUNCTION>();
            this.TB_MASTER_DATA_SUB_CATEGORY = new HashSet<TB_MASTER_DATA_SUB_CATEGORY>();
        }
    
        public int Data_Cat_ID { get; set; }
        public Nullable<int> Data_Type_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_JOB_FUNCTION> TB_JOB_SEEKER_JOB_FUNCTION { get; set; }
        public virtual TB_MASTER_DATA_TYPE TB_MASTER_DATA_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MASTER_DATA_SUB_CATEGORY> TB_MASTER_DATA_SUB_CATEGORY { get; set; }
    }
}
