//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPLOYER
    {
        public int Employer_ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Move_in_date { get; set; }
        public Nullable<int> Move_out_date { get; set; }
        public string Employer_Name { get; set; }
        public Nullable<int> Company_ID { get; set; }
    }
}
