//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_POST_JOB_FUNCTION
    {
        public int ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Data_Sub_Cat_ID { get; set; }
    
        public virtual TB_MASTER_DATA_SUB_CATEGORY TB_MASTER_DATA_SUB_CATEGORY { get; set; }
    }
}
