//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER_CV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_JOB_SEEKER_CV()
        {
            this.TB_JOB_APPLICAITON = new HashSet<TB_JOB_APPLICAITON>();
            this.TB_JOB_APPLICANT_CV_ACTION_HISTORY = new HashSet<TB_JOB_APPLICANT_CV_ACTION_HISTORY>();
            this.TB_JOB_SEEKER_ACHIEVEMENT = new HashSet<TB_JOB_SEEKER_ACHIEVEMENT>();
            this.TB_JOB_SEEKER_CERTIFICATE = new HashSet<TB_JOB_SEEKER_CERTIFICATE>();
            this.TB_JOB_SEEKER_EDUCATION = new HashSet<TB_JOB_SEEKER_EDUCATION>();
            this.TB_JOB_SEEKER_JOB_FUNCTION = new HashSet<TB_JOB_SEEKER_JOB_FUNCTION>();
            this.TB_JOB_SEEKER_SKILL_KEYWORD = new HashSet<TB_JOB_SEEKER_SKILL_KEYWORD>();
            this.TB_JOB_SEEKER_WORK_EXPERIENCE = new HashSet<TB_JOB_SEEKER_WORK_EXPERIENCE>();
        }
    
        public int JobSeeker_CV_ID { get; set; }
        public Nullable<int> JobSeeker_ID { get; set; }
        public Nullable<int> Education_Level { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Expected_Salary { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<System.DateTime> Available_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_APPLICAITON> TB_JOB_APPLICAITON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_APPLICANT_CV_ACTION_HISTORY> TB_JOB_APPLICANT_CV_ACTION_HISTORY { get; set; }
        public virtual TB_JOB_SEEKER TB_JOB_SEEKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_ACHIEVEMENT> TB_JOB_SEEKER_ACHIEVEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_CERTIFICATE> TB_JOB_SEEKER_CERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_EDUCATION> TB_JOB_SEEKER_EDUCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_JOB_FUNCTION> TB_JOB_SEEKER_JOB_FUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_SKILL_KEYWORD> TB_JOB_SEEKER_SKILL_KEYWORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_SEEKER_WORK_EXPERIENCE> TB_JOB_SEEKER_WORK_EXPERIENCE { get; set; }
    }
}
