//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER_SEARCH_HISTORY
    {
        public int ID { get; set; }
        public Nullable<int> JobSeeker_ID { get; set; }
        public Nullable<int> Job_Function { get; set; }
        public Nullable<int> Paid_Type { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Education_Level { get; set; }
        public Nullable<int> Employment_Type { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<int> Search_Type { get; set; }
        public string Search_Keyword { get; set; }
    }
}
