//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER_COVER_LETTER
    {
        public int ID { get; set; }
        public Nullable<int> JobSeeker_ID { get; set; }
        public string Content { get; set; }
    
        public virtual TB_JOB_SEEKER TB_JOB_SEEKER { get; set; }
    }
}
