//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_SEEKER_EDUCATION
    {
        public int ID { get; set; }
        public Nullable<int> JobSeeker_CV_ID { get; set; }
        public string Educated_From { get; set; }
        public string Educated_To { get; set; }
        public string Institution { get; set; }
        public string Education_Level { get; set; }
        public string Major { get; set; }
        public string GPA { get; set; }
    
        public virtual TB_JOB_SEEKER_CV TB_JOB_SEEKER_CV { get; set; }
    }
}
