//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MASTER_DATA_SUB_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MASTER_DATA_SUB_CATEGORY()
        {
            this.TB_JOB_POST = new HashSet<TB_JOB_POST>();
            this.TB_JOB_POST_JOB_FUNCTION = new HashSet<TB_JOB_POST_JOB_FUNCTION>();
        }
    
        public int Data_Sub_Cat_ID { get; set; }
        public Nullable<int> Data_Cat_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST> TB_JOB_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JOB_POST_JOB_FUNCTION> TB_JOB_POST_JOB_FUNCTION { get; set; }
        public virtual TB_MASTER_DATA_CATEGORY TB_MASTER_DATA_CATEGORY { get; set; }
    }
}
