//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSTP.TalentPool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RELATED_JOB_POST
    {
        public int ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Related_Job_ID { get; set; }
        public Nullable<int> View_Count { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
    
        public virtual TB_JOB_POST TB_JOB_POST { get; set; }
        public virtual TB_JOB_POST TB_JOB_POST1 { get; set; }
    }
}
